[package]
name = "eidetic-core"
version = "0.4.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Shared types and configuration for Eidetic."

[dependencies]
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
kamadak-exif = { workspace = true }
thiserror = { workspace = true }
ureq = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
