[package]
name = "eidetic-cli"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Eidetic command-line interface."

[[bin]]
name = "eidetic"
path = "src/main.rs"

[dependencies]
eidetic-core = { path = "../eidetic-core" }
eidetic-ingest = { path = "../eidetic-ingest" }
eidetic-db = { path = "../eidetic-db" }
eidetic-ml = { path = "../eidetic-ml" }
eidetic-server = { path = "../eidetic-server" }
serde_json = { workspace = true }
csv = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
